openapi: 3.0.3
info:
  title: PIP VC Service
  version: 1.0.0
  description: PIP VC Service API for the PDS3.0 project
servers:
  - url: http://localhost:3002
    description: Local development server
paths:
  /login:
    post:
      summary: Authenticate using Solid OIDC
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                redirect_uri:
                  type: string
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /eligibility:
    get:
      summary: Get PIP award mock data
      security:
        - bearerAuth: []
      responses:
        '200':
          description: PIP eligibility data
          content:
            application/json:
              schema:
                type: object
                properties:
                  benefitType:
                    type: string
                    example: PIP
                  amount:
                    type: string
                    example: £90.10/week
  /vc/preview:
    get:
      summary: Preview VC before issuing
      security:
        - bearerAuth: []
      responses:
        '200':
          description: VC preview
          content:
            application/json:
              schema:
                type: object
            application/ld+json:
              schema:
                type: object
            text/turtle:
              schema:
                type: string
  /vc/issue:
    post:
      summary: Issue VC to user pod
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                webid:
                  type: string
      responses:
        '200':
          description: VC issued
          content:
            application/json:
              schema:
                type: object
                properties:
                  vc:
                    type: object
                  vcId:
                    type: string
  /vc/list:
    get:
      summary: List issued VCs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of VCs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    issuanceDate:
                      type: string
                    status:
                      type: string
  /vc/revoke:
    post:
      summary: Revoke credential
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                vcId:
                  type: string
                reason:
                  type: string
      responses:
        '200':
          description: VC revoked
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
